-- MySQL Script generated by MySQL Workbench
-- Tue 18 Jan 2022 12:39:17 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PortalWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PortalWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PortalWeb` ;
USE `PortalWeb` ;

-- -----------------------------------------------------
-- Table `PortalWeb`.`Distribuidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortalWeb`.`Distribuidor` (
  `codigo` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `correoNotificacion` VARCHAR(60) NULL,
  `correoAlerta` VARCHAR(60) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalWeb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortalWeb`.`Producto` (
  `codigo` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL,
  `monto` DOUBLE NULL,
  `distribuidor` BIGINT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Productos_Distribuidores_idx` (`distribuidor` ASC),
  CONSTRAINT `fk_Productos_Distribuidores`
    FOREIGN KEY (`distribuidor`)
    REFERENCES `PortalWeb`.`Distribuidor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalWeb`.`CanalAutorizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortalWeb`.`CanalAutorizado` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `distribuidor` BIGINT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_CanalesAutorizados_Distribuidores1_idx` (`distribuidor` ASC),
  CONSTRAINT `fk_CanalesAutorizados_Distribuidores1`
    FOREIGN KEY (`distribuidor`)
    REFERENCES `PortalWeb`.`Distribuidor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
